-- sys 계정으로
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER tlink IDENTIFIED BY tlink1234;
GRANT CONNECT, RESOURCE TO tlink;
ALTER USER tlink DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;