
--테이블 삭제
DROP TABLE "VIDEO_MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "VIDEO_CHAT" CASCADE CONSTRAINTS;
DROP TABLE "VIDEO_CHATTIMER" CASCADE CONSTRAINTS;
DROP TABLE "VIDEO_ROOM" CASCADE CONSTRAINTS;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_CHAT_NO;
DROP SEQUENCE  SEQ_TIMER_NO;


CREATE TABLE "VIDEO_MEMBER" (
	"PROJECT_NO"	NUMBER		NOT NULL,
	"USER_NO"	    NUMBER		NOT NULL,
	"VIDEO_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
    PRIMARY KEY (USER_NO, PROJECT_NO),
    CONSTRAINT FK_USER_VIDEO_MEMBER FOREIGN KEY (USER_NO) REFERENCES "USER" (USER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_PROJECT_VIDEO_MEMBER FOREIGN KEY (PROJECT_NO) REFERENCES "PROJECT" (PROJECT_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN "VIDEO_MEMBER"."PROJECT_NO" IS '프로젝트 번호';
COMMENT ON COLUMN "VIDEO_MEMBER"."USER_NO" IS '사용자 번호';
COMMENT ON COLUMN "VIDEO_MEMBER"."VIDEO_STATUS" IS '접속중 Y 나감 N';


CREATE TABLE "VIDEO_ROOM" (
	"PROJECT_NO"	NUMBER		NOT NULL,
	"VIDEO_TITLE"	VARCHAR2(100)	DEFAULT '화상 채팅'	NOT NULL , 
    PRIMARY KEY (PROJECT_NO),
    CONSTRAINT FK_MEMBER_VIDEO_ROOM FOREIGN KEY (PROJECT_NO) REFERENCES "PROJECT" (PROJECT_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN "VIDEO_ROOM"."PROJECT_NO" IS '프로젝트 번호';
COMMENT ON COLUMN "VIDEO_ROOM"."VIDEO_TITLE" IS '제목';


CREATE TABLE "VIDEO_CHATTIMER" (
	"TIMER_NO"	NUMBER		NOT NULL,
	"TIMER_SEND"	DATE		NOT NULL,
	"TIMER_CONTENT"	VARCHAR2(600)	NOT NULL,
	"TIMER_STATUS"	VARCHAR2(3)	DEFAULT 'N'	NOT NULL,
	"PROJECT_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
    PRIMARY KEY (TIMER_NO),
    CONSTRAINT FK_VIDEO_MEMBER_CHATTIMER FOREIGN KEY (USER_NO, PROJECT_NO) 
    REFERENCES "VIDEO_MEMBER" (USER_NO, PROJECT_NO) ON DELETE CASCADE 
);

COMMENT ON COLUMN "VIDEO_CHATTIMER"."TIMER_NO" IS '예약 번호(SEQ)';
COMMENT ON COLUMN "VIDEO_CHATTIMER"."TIMER_SEND" IS '예약 시간';
COMMENT ON COLUMN "VIDEO_CHATTIMER"."TIMER_CONTENT" IS '메시지 내용';
COMMENT ON COLUMN "VIDEO_CHATTIMER"."TIMER_STATUS" IS '전송시 Y';
COMMENT ON COLUMN "VIDEO_CHATTIMER"."PROJECT_NO" IS '프로젝트 번호';
COMMENT ON COLUMN "VIDEO_CHATTIMER"."USER_NO" IS '사용자 번호';



CREATE TABLE "VIDEO_CHAT" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"CHAT_TIMESTAMP"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_CONTENT"	VARCHAR2(600)		NOT NULL,
	"PROJECT_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
    PRIMARY KEY (CHAT_NO),
    CONSTRAINT FK_MEMBER_VIDEO_CHAT FOREIGN KEY (USER_NO,PROJECT_NO) REFERENCES "VIDEO_MEMBER" (USER_NO,PROJECT_NO) ON DELETE CASCADE
    
);

COMMENT ON COLUMN "VIDEO_CHAT"."CHAT_NO" IS '채팅 번호';
COMMENT ON COLUMN "VIDEO_CHAT"."CHAT_TIMESTAMP" IS '채팅 시간';
COMMENT ON COLUMN "VIDEO_CHAT"."CHAT_CONTENT" IS '채팅내용';
COMMENT ON COLUMN "VIDEO_CHAT"."PROJECT_NO" IS '프로젝트 번호';
COMMENT ON COLUMN "VIDEO_CHAT"."USER_NO" IS '사용자 번호';




-- 시퀀스 생성
CREATE SEQUENCE SEQ_CHAT_NO NOCACHE;
CREATE SEQUENCE SEQ_TIMER_NO NOCACHE;

SELECT * FROM "VIDEO_MEMBER";
SELECT * FROM "VIDEO_ROOM";
SELECT * FROM VIDEO_CHAT;
SELECT * FROM VIDEO_CHATTIMER;
select * from "USER";
SELECT CHAT_CONTENT ,CHAT_TIMESTAMP FROM VIDEO_CHAT WHERE PROJECT_NO=1 ORDER BY CHAT_NO;
SELECT USER_NAME, CHAT_CONTENT, CHAT_TIMESTAMP,PROFILE_IMG FROM VIDEO_CHAT JOIN "USER" USING(USER_NO) WHERE PROJECT_NO=1 ORDER BY CHAT_NO;
--ROLLBACK;
-- 샘플 데이터 삽입
--INSERT INTO "VIDEO_MEMBER" VALUES (1, 1, 'Y');
--INSERT INTO "VIDEO_MEMBER" VALUES (1, 2, 'Y');
INSERT INTO "VIDEO_ROOM" VALUES (1, DEFAULT);
INSERT INTO VIDEO_CHAT VALUES (SEQ_CHAT_NO.NEXTVAL, SYSDATE, '안녕', 1 , 1);
INSERT INTO VIDEO_CHATTIMER VALUES (SEQ_TIMER_NO.NEXTVAL , SYSDATE, '내용', 'N' , 1, 1);
--ROLLBACK;
--UPDATE "VIDEO_MEMBER" SET VIDEO_STATUS='N' WHERE USER_NO=4;
UPDATE VIDEO_ROOM SET VIDEO_TITLE='점심 뭐' WHERE PROJECT_NO=1;
UPDATE VIDEO_ROOM SET VIDEO_TITLE='test' WHERE PROJECT_NO=1;
UPDATE VIDEO_MEMBER SET VIDEO_STATUS='N' WHERE PROJECT_NO=1 AND USER_NO=1;
UPDATE VIDEO_CHATTIMER SET TIMER_STATUS='Y' WHERE PROJECT_NO =1 AND USER_NO=1;
commit;
SELECT VIDEO_TITLE FROM VIDEO_ROOM WHERE PROJECT_NO=1;
SELECT SYSDATE FROM DUAL;
-- 날자 입력방식 변경
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-RR';

exit;

SELECT USER_NO FROM THREAD_MEMBER WHERE THREAD_NO=#{};




CREATE TABLE "THREAD" (
	"THREAD_NO"	NUMBER		NOT NULL,
	"THREAD_TITLE"	VARCHAR2(100)		NOT NULL,
    PRIMARY KEY (THREAD_NO)
);

COMMENT ON COLUMN "THREAD"."THREAD_NO" IS '스레드 번호(SEQ)';

COMMENT ON COLUMN "THREAD"."THREAD_TITLE" IS '스레드 이름';

CREATE TABLE "THREAD_MESSAGE" (
	"THREAD_CHATNO"	NUMBER		NOT NULL,
	"THREAD_MESSAGE"	VARCHAR2(4000)		NOT NULL,
	"THREAD_TIMESTAMP"	DATE	DEFAULT SYSDATE	NOT NULL,
	"THREAD_TYPE"	VARCHAR2(100)		NOT NULL,
	"THREAD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
    PRIMARY KEY (THREAD_CHATNO),
    FOREIGN KEY (THREAD_NO) REFERENCES THREAD(THREAD_NO) ON DELETE CASCADE, -- 외래 키 설정
    FOREIGN KEY (USER_NO) REFERENCES "USER"(USER_NO) ON DELETE CASCADE -- 외래 키 설정
);

COMMENT ON COLUMN "THREAD_MESSAGE"."THREAD_CHATNO" IS '채팅 번호(SEQ)';

COMMENT ON COLUMN "THREAD_MESSAGE"."THREAD_MESSAGE" IS '채팅 내용';

COMMENT ON COLUMN "THREAD_MESSAGE"."THREAD_TIMESTAMP" IS '채팅 시간';

COMMENT ON COLUMN "THREAD_MESSAGE"."THREAD_TYPE" IS '"ENTER" / "CHAT"/"SYSTEM"';

COMMENT ON COLUMN "THREAD_MESSAGE"."THREAD_NO" IS '스레드 번호(SEQ)';

COMMENT ON COLUMN "THREAD_MESSAGE"."USER_NO" IS '사용자 번호';

CREATE TABLE "THREAD_MEMBER" (
	"THREAD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
    FOREIGN KEY (THREAD_NO) REFERENCES THREAD(THREAD_NO) ON DELETE CASCADE, -- 외래 키 설정
    FOREIGN KEY (USER_NO) REFERENCES "USER"(USER_NO) ON DELETE CASCADE -- 외래 키 설정
);

COMMENT ON COLUMN "THREAD_MEMBER"."THREAD_NO" IS '스레드 번호(SEQ)';

COMMENT ON COLUMN "THREAD_MEMBER"."USER_NO" IS '사용자 번호';

CREATE TABLE "PROJECT THREAD" (
	"PROJECT_NO"	NUMBER		NOT NULL,
	"THREAD_NO"	NUMBER		NOT NULL,
    FOREIGN KEY (THREAD_NO) REFERENCES THREAD(THREAD_NO) ON DELETE CASCADE, -- 외래 키 설정
    FOREIGN KEY (PROJECT_NO) REFERENCES "PROJECT"(PROJECT_NO) ON DELETE CASCADE -- 외래 키 설정
);

COMMENT ON COLUMN "PROJECT THREAD"."PROJECT_NO" IS '프로젝트 번호';

COMMENT ON COLUMN "PROJECT THREAD"."THREAD_NO" IS '스레드 번호(SEQ)';



--- insert에 있던 work 이동


--------------------------------------------------------------------------------
--작업

INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('1', '프론트 작업1', '프론트입니다. 작업1 내용', '2024-08-24 09:12:23', '', '2024-09-29 00:00:00', '1', '0', '0', '3', '', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('2', '프론트 작업2', '프론트입니다. 작업2 내용', '2024-09-15 09:12:23', '', '2024-09-26 00:00:00', '1', '1', '1', '3', '1', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('3', '프론트 작업3', '프론트입니다. 작업3 내용', '2024-09-23 09:12:23', '', '2024-09-25 09:12:23', '1', '1', '1', '3', '2', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('4', '프론트 작업4', '프론트입니다. 작업4 내용', '2024-09-26 09:12:23', '', '2024-10-25 00:00:00', '1', '1', '1', '3', '3', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('5', '프론트 작업5', '프론트입니다. 작업5 내용', '2024-09-25 09:12:23', '', '2024-10-27 00:00:00', '1', '1', '1', '3', '2', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('6', '프론트 작업6', '프론트입니다. 작업6 내용', '2024-10-01 09:12:23', '', '2024-10-25 09:12:23', '1', '2', '1', '3', '2', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('7', '프론트 작업7', '프론트입니다. 작업7 내용', '2024-09-25 09:12:23', '', '2024-10-12 00:00:00', '1', '1', '1', '3', '3', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('8', '백앤드 작업1', '백앤드입니다. 작업1 내용', '2024-10-15 09:12:23', '', '2024-10-15 00:00:00', '1', '0', '0', '4', '6', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('9', '백앤드 작업2', '백앤드입니다. 작업2 내용', '2024-10-10 09:12:23', '', '2024-10-30 00:00:00', '1', '0', '0', '4', '7', '1');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('10', '백앤드 작업3', '백앤드입니다. 작업3 내용', '2024-10-25 09:12:23', '', '2024-10-30 00:00:00', '1', '0', '0', '4', '9', '1');


INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('11', '프론트 작업1', '프론트입니다. 작업1 내용', '2024-08-24 09:12:23', '', '2024-09-29 00:00:00', '1', '0', '0', '3', '', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('12', '프론트 작업2', '프론트입니다. 작업2 내용', '2024-09-15 09:12:23', '', '2024-09-26 00:00:00', '1', '1', '1', '3', '1', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('13', '프론트 작업3', '프론트입니다. 작업3 내용', '2024-09-23 09:12:23', '', '2024-09-25 09:12:23', '1', '1', '1', '3', '2', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('14', '프론트 작업4', '프론트입니다. 작업4 내용', '2024-09-26 09:12:23', '', '2024-10-25 00:00:00', '1', '1', '1', '3', '3', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('15', '프론트 작업5', '프론트입니다. 작업5 내용', '2024-09-25 09:12:23', '', '2024-10-27 00:00:00', '1', '1', '1', '3', '2', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('16', '프론트 작업6', '프론트입니다. 작업6 내용', '2024-10-01 09:12:23', '', '2024-10-25 09:12:23', '1', '2', '1', '3', '2', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('17', '프론트 작업7', '프론트입니다. 작업7 내용', '2024-09-25 09:12:23', '', '2024-10-12 00:00:00', '1', '1', '1', '3', '3', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('18', '백앤드 작업1', '백앤드입니다. 작업1 내용', '2024-10-15 09:12:23', '', '2024-10-15 00:00:00', '1', '0', '0', '4', '6', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('19', '백앤드 작업2', '백앤드입니다. 작업2 내용', '2024-10-10 09:12:23', '', '2024-10-30 00:00:00', '1', '0', '0', '4', '7', '2');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('20', '백앤드 작업3', '백앤드입니다. 작업3 내용', '2024-10-25 09:12:23', '', '2024-10-30 00:00:00', '1', '0', '0', '4', '9', '2');


INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('21', '프론트 작업1', '프론트입니다. 작업1 내용', '2024-08-24 09:12:23', '', '2024-09-29 00:00:00', '1', '0', '0', '3', '', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('22', '프론트 작업2', '프론트입니다. 작업2 내용', '2024-09-15 09:12:23', '', '2024-09-26 00:00:00', '1', '1', '1', '3', '1', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('23', '프론트 작업3', '프론트입니다. 작업3 내용', '2024-09-23 09:12:23', '', '2024-09-25 09:12:23', '1', '1', '1', '3', '2', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('24', '프론트 작업4', '프론트입니다. 작업4 내용', '2024-09-26 09:12:23', '', '2024-10-25 00:00:00', '1', '1', '1', '3', '3', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('25', '프론트 작업5', '프론트입니다. 작업5 내용', '2024-09-25 09:12:23', '', '2024-10-27 00:00:00', '1', '1', '1', '3', '2', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('26', '프론트 작업6', '프론트입니다. 작업6 내용', '2024-10-01 09:12:23', '', '2024-10-25 09:12:23', '1', '2', '1', '3', '2', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('27', '프론트 작업7', '프론트입니다. 작업7 내용', '2024-09-25 09:12:23', '', '2024-10-12 00:00:00', '1', '1', '1', '3', '3', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('28', '백앤드 작업1', '백앤드입니다. 작업1 내용', '2024-10-15 09:12:23', '', '2024-10-15 00:00:00', '1', '0', '0', '4', '6', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('29', '백앤드 작업2', '백앤드입니다. 작업2 내용', '2024-10-10 09:12:23', '', '2024-10-30 00:00:00', '1', '0', '0', '4', '7', '3');
INSERT INTO WORK (WORK_NO, WORK_TITLE, WORK_CONTENT,CREATE_DT, UPDATE_DT, DUE_DT, WORK_ST, WORK_PR_ST, WORK_PR, WORK_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('30', '백앤드 작업3', '백앤드입니다. 작업3 내용', '2024-10-25 09:12:23', '', '2024-10-30 00:00:00', '1', '0', '0', '4', '9', '3');
COMMIT;


--댓글
INSERT INTO WORK_COMMENT (COMMENT_NO, COMMENT_CON, COMMENT_ST, COMMENT_DT, PARENT_NO, WORK_NO, USER_NO) VALUES ('1', '댓글1 입니다.', '1', '2024-09-25 10:13:38', '', '1', '3');
INSERT INTO WORK_COMMENT (COMMENT_NO, COMMENT_CON, COMMENT_ST, COMMENT_DT, PARENT_NO, WORK_NO, USER_NO) VALUES ('2', '댓글2 입니다.', '1', '2024-09-25 10:13:38', '', '1', '4');
INSERT INTO WORK_COMMENT (COMMENT_NO, COMMENT_CON, COMMENT_ST, COMMENT_DT, PARENT_NO, WORK_NO, USER_NO) VALUES ('3', '댓글3 입니다.', '1', '2024-09-25 10:13:38', '', '1', '3');
INSERT INTO WORK_COMMENT (COMMENT_NO, COMMENT_CON, COMMENT_ST, COMMENT_DT, PARENT_NO, WORK_NO, USER_NO) VALUES ('4', '댓글4 입니다.', '1', '2024-09-25 10:13:38', '', '1', '4');
INSERT INTO WORK_COMMENT (COMMENT_NO, COMMENT_CON, COMMENT_ST, COMMENT_DT, PARENT_NO, WORK_NO, USER_NO) VALUES ('5', '댓글5 입니다.', '1', '2024-09-25 10:13:38', '', '1', '3');
COMMIT;


--투두
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('1', '제목1', '내용1', '2024-09-23 10:20:13', '', '1', '0', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('2', '제목2', '내용2', '2024-09-23 10:20:15', '', '1', '0', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('3', '제목3', '내용3', '2024-09-23 10:20:22', '', '1', '0', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('4', '제목4', '내용4', '2024-09-23 10:50:13', '', '1', '0', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('5', '제목5', '내용5', '2024-09-23 10:50:13', '', '1', '0', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('6', '제목6', '내용6', '2024-09-23 10:50:13', '', '1', '1', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('7', '제목7', '내용7', '2024-09-23 10:50:14', '', '1', '1', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('8', '제목8', '내용8', '2024-09-23 11:20:18', '', '1', '1', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('9', '제목9', '내용9', '2024-09-23 13:09:50', '', '1', '1', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('10', '제목10', '내용10', '2024-09-23 13:11:57', '', '1', '1', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('11', '제목11', '내용11', '2024-09-23 13:13:08', '', '1', '2', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('12', '제목12', '내용12', '2024-09-23 13:19:04', '', '1', '2', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('13', '제목13', '내용13', '2024-09-23 13:19:07', '', '1', '2', '3', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('14', '제목14', '내용14', '2024-09-23 13:19:09', '', '1', '2', '4', '', '1');
INSERT INTO TODO (TODO_NO, TODO_TITLE, TODO_CONTENT, CREATE_DT, UPDATE_DT, TODO_ST, TODO_PR_ST, TODO_MN_NO, PARENT_NO, PROJECT_NO) VALUES ('15', '제목15', '내용15', '2024-09-23 13:23:35', '', '1', '2', '4', '', '1');
COMMIT;





